#!/bin/sh 
# Fix for BeOS build
echo Configuring the package for BeOS
cat <<EOF > makefile
# generated by fixbe.sh
include mkfiles/makefile.cfg
include mkfiles/makefile.be

include mkfiles/makefile.all
-include \$(OBJDIR)/makefile.dep
EOF

echo Done!