#!/bin/sh 
# Fix for Unix (Linux) build
echo Configuring the package for Unix
cat <<EOF > makefile
# generated by fixunix.sh
include mkfiles/makefile.cfg
include mkfiles/makefile.unx
include mkfiles/makefile.all
-include \$(OBJDIR)/makefile.dep
EOF

echo Done!